# Permalinks
permalink: pretty

# Setup
title: "This dayâ€™s portion"
tagline: One of your five a day, every day, in imagistic and paragraphical formats
paginate: 5
lang: en-gb
credit: yes
feedurl: "https://www.thisdaysportion.xyz"

# Gems
gems:
  - jekyll-paginate
