# Permalinks
permalink: pretty

# Setup
title: "This dayâ€™s portion"
tagline: One of your five a day, every day, in imagistic and paragraphical formats
paginate: 10
lang: en-gb
credit: yes

# Gems
gems:
  - jekyll-paginate
